### ISSUE TITLE
Вопросы и предложения к статье.

### ISSUE THREAD

**Issue by andriytyurnikov** [x-raizor/graphic-tension-simulator#1]
Здравствуйте Андрей, Игорь.

К сожалению, не нашел ваш e-mail, в связи с чем свои вопросы и предложения к статье 
http://ashapiro.ru/research/graphic-tension-simulator/ высылаю через гитхаб (:

Первым делом конечно же поздравляю вас с тем, что довели работу до некоторого 
законченного этапа.
Благодарю вас и Игоря за то, что вы поделились результатами своего труда с сообществом.

В свое время, размышляя над схожим вопросом 
"как элементы композиции делят между собой пространство", 
я думал о визуализации принципа, заложенного в разбиениях Вороного 
(который для двух точек подразумевает проведение разделительной линии на середине расстояния между точками), 
о тех временах напоминает этот заброшенный jsbin 
(там потребуется навести мышку на прямоугольник в правой части экрана) 
http://jsbin.com/nabixi/4/edit?html,css,js,output

Первой приятной новостью был, конечно, Multiclick, а после выхода вашей работы - появилось 
приятное ощущение, что актуализация темы происходит в умах многих, и я не сдержался от написания этого письма

Ваш труд явно показал, что может быть, не за пару выходных, но вполне возможно построить
инструмент трансформирующий понимание композиции.

Ознакомившись с вашей статьей по предмету и с симулятором, я
неожиданно сильно обрадовался, и решил поделиться с вами своими соображениями по схожей проблематике

#1 **Опциональность активной рамки** -- оперируя статичными разбиениями Вороного в своих экспериментах я ввел активную рамку для обыгрывания гипотезы о том, что чистый лист содержит неоднородную напряженность обусловленную формой самого листа. 
С удовольствием отметил в исходном коде вашего симулятора возможность отключить эту рамку. К сожалению, в Кулоновской модели, удаление рамки во время динамической симуляции ведет к разлету точек в бесконечность (:
При этом я нахожу подход без активной рамки - как минимум любопытным, для моделирования взаимного влияния элементов группы - без учета влияния окружения - очевидно, что начальное напряжение "сцены" обусловленно прямоугольной формой этой сцены.
Кроме варианта "статика" - есть забавная мысль о введении эквивалента "трения покоя" - 
некоторой граничной величины псевдокулоновской силы, требуемой для минимальной динамики -- что, кстати, поможет и с описанной ниже проблемой равновесия.

#2 **Недостатки точечной и кулоновской моделей** -- модель точки проста и понятна, вместе с тем очевидна ее ограниченность, и это задача которую рано или поздно неизбежно придется решать, по моему скромному мнению. 
В Кулоновской или Ньютоновской модели широко использован принцип суперпозиции, позволяющий заменить тело материальной точкой - расположенной в центре масс тела. 
И в этом смысле все здорово -- виден путь к относительно тривиальному следующему шагу развития.
Призываю вас, однако, хотя-бы ради мысленного эксперимента, рассмотреть модель, 
в которой взаимодейсвие двух тел идет не с учетом расстояния между центрами их масс, 
а с учетом кратчайшего расстояния между телами -- иными словами - даже "легкие" элементы 
в чрезмерной близости -- могут сильно "напрягать" -- можно представить класс задач, к которых размеры тел будут варьироваться (например -- список твитов), а их вес (смысловой вес) - условно равен, и иметь равные отступы между такими элементами - возможно неплохой вариант.

#3 **Проблема равновесия**
Такие явления как точки Лагранжа, эффект бабочки, проблема локального максимума и 
неразрешимость (в общем случае) проблемы трех тел - удивительным образом 
имеют отношение к вашей симуляции - возможно вы наблюдали случаи, 
когда точку не получалось поставить на одной оси с остальными, например
https://cl.ly/0V0Z1p1Y0s0e
Это связанно с тем, что область локального минимума поля, вдоль горизонтальной оси сцены --
хоть и существует, но невелика, и при промахе в пол-корпуса, пользователь может в нее не попасть. 

Визуализация точек минимума напряжения, центров фигур, опция "snap to point" для интерфейса, и введение "трения покоя" могут помочь с этой проблемой.

#4 **Поправочные коэфициенты и суперпозиция полей.**
Площадь краски на листе - важный параметр - кроме шуток. 
Однако, у контента есть много измерений кроме площади: новизна, эмоциональный индекс, порядок следования в списке, популярность, важность, достоверность и т.д. -- каждый из этих пунктов - отдельная большая тема, и кстати - упоминание того, что "не все так просто в дизайне" - частый довод в скептических оценках перспектив автоматизации дизайна.

Вот, например: http://scotthurff.com/posts/how-to-design-for-thumbs-in-the-era-of-huge-screens
А что если дизайнер не желает "на глазок" делать поправки на важность или досягаемость 
пальцем на смартфоне элементов интерфейса?

В максимуме, представьте себе процесс формирования композиции 
в нескольких полях напряжености сразу: для управляющих элементов -- поле досягаемости пальцем на телефонах, сылки на статьи взаимодействуют в полях новизны и популярности, 
рекламные элементы взаимодействуют в полях прибыльности... мечты, мечты)

Простейшим решением было введение поправочных коэфициентов для фигур, 
возможно поможет отображение доли веса текущего элемента среди их всех -- 
чтобы не надеятся на глазомер.

#5 **Визуализация поля.**
Есть надежда, что heatmap будет более удачной визуализацией неоднородного 
поля чем "магнитные линии" (рендеринг которых все тормозит, кстати).

Надеюсь мое письмо не отняло у вас слишком много времени.

Еще раз большое спасибо вам за то, что поделились своей работой,
уверен, что она приведет вас и не только вас к новому пониманию композиции.

С уважением,
Андрей Тюрников

**Comment by x-raizor** [comment]
@andriytyurnikov это прекрасное письмо, Андрей. О такой обратной связи мечтает любой исследователь. Спасибо за ваш интерес и идеи, это нас здорово поддерживает. Напишу чуть позднее вам на почту, чтобы обсудить ваши идеи. Моя почта — andrew@ashapiro.ru. Почта Игоря —  conversive@mail.ru

**Comment by andriytyurnikov** [comment]
@x-raizor, глянь сюда https://github.com/andriytyurnikov/graphic-tension-simulator/pull/1
Редуцированная визуализация -- зло -- только heatmap (:
Кроме производительности, heatmap требует еще и аккуратного преобразования квадратично распределенной величины в линейную, и кстати - разница в напряженности поля около объектов - пропорциональная отношению площадей объектов - а это запросто в разы - на примерах с крупными и мелкими зарядами - это видно.
Уверен -- возня с настройками heatmap - стоит свеч - сфокусируюсь на этом.

**Comment by andriytyurnikov** [comment]
@x-raizor - кстати - есть мысль, что можно держать в памяти векторное поле каждого объекта, и перейти к операциям над векторными полями, вместо вагона Кулоновских умножений в каждой точке (;

**Comment by x-raizor** [comment]
@andriytyurnikov работать с векторизацией вместо квадратичного по времени цикла — правильная идея, тоже планировал это сделать.

**Comment by andriytyurnikov** [comment]
@x-raizor , check this out http://blogoscoped.com/click2/

**Comment by x-raizor** [comment]
@andriytyurnikov that's cool, I like it. Thanks

**Comment by andriytyurnikov** [comment]
@x-raizor, в прошлый подход к снаряду меня достаточно сильно демотивировала разница между диаграмами кулоновской модели, мультиклика и записок Арнхейма)
В нынешний период я увлечен гипотезой о том, что эти диаграммы - лишь отображение некторого процесса (протяженного во вемени) с транспортно-геометрической и вероятностной природой - возможно с "алгоритмами" движения глаз при сканировании сцен. Хочеться понять процесс который моделируется, прежде чем его моделировать :) Не стесняйтесь делиться новостями, если таковые возникнут)

**Comment by x-raizor** [comment]
@andriytyurnikov в настоящее время двигаюсь по пути машинного обучения. В этом подходе неважно какова природа явления. Если интересно, присоединяйтесь.

**Comment by andriytyurnikov** [comment]
https://perceptual.mpi-inf.mpg.de/files/2016/02/xu16_chi.pdf

**Comment by andriytyurnikov** [comment]
@x-raizor Собственно приехали https://www.attentioninsight.com/ -- и это, как минимум, вторые.
Последние часов 18 читал про наработки в этой области - собственно - пора внедрять - исследований уже вагоны. Конечно про равновесие, напряженность и прочий гештальт прийдется забыть -- но в этом же и смысл?)
Вы если не утратили интерес еще - то может побрейнштормим?
Там просто очень много вкусного кроме дизайна вырастает - автоматическая оценка фотографий товаров, например.

**Comment by andriytyurnikov** [comment]
https://feng-gui.com/science

**Comment by x-raizor** [comment]
@andriytyurnikov оценка картинки мало интересует. Интересуют генеративные техники. Если есть конкретные предложения о прогрессе в области размещения объектов на плоскости, буду рад обсудить.
